name: food_1
description: Smart recipe app with contextual suggestions, offline support & notifications.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1

  # Networking
  http: ^1.2.1

  # Local persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Image caching
  cached_network_image: ^3.3.1

  # Location
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

  # UI
  shimmer: ^3.0.0

  # URL launcher
  url_launcher: ^6.3.0

  # Connectivity
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true